name:                mroW
version:             0.1.0.0
category:            Game
synopsis:            It's a game
github:              "andreeL/mroW"
author:              "Andrée Lindgren"
maintainer:          "N/A"
copyright:           "2017-2018 Author Andrée Lindgren"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/andreeL/mroW#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- freetype2
- GLFW-b
- linear
- microlens-platform
- OpenGLRaw
- primitive
- random
- sdl2
- stm
- vector

library:
  source-dirs: src

executables:
  mroW-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mroW

tests:
  RankSelect-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mroW
